version: 2

jobs:
  build:
    docker:
      - image: integrationcheckout/ecommerce:wordpress4.9.2.wocommerce3.2.6
    working_directory: ~/cko_wp
    steps:
      - checkout
      - run:
          name: Refresh Wordpress and Install Checkout
          command: |
            sudo service apache2 restart && sudo service mysql restart
            cd /var/www/html/wordpress/wp-content/plugins/ && sudo mv ~/cko_wp/woocommerce-gateway-checkout-com .
      - run:
          name: Install dependencies
          command: |
            cd ~/cko_wp/tests && npm i
      - run:
          name: Run Testss
          command: |
            cd ~/cko_wp/tests && npm test
      - store_artifacts:
          path: ~/cko_wp/tests/cypress/videos
          destination: Recorded-Tests
